Fixes #503
source-academy/sicp pull request #521
Opened 2021-06-07 21:32 UTC by TobiasWrigstad

Reduces leading space by 2pts. But I thought it was better balanced
before. What's your opinion?

2021-06-07 23:59 UTC, martin-henz requested changes
You only changed the leading space, not the trailing space. 

Can we have the same leading and trailing space as for the multi-line parse equations?

(I just measured with a ruler on the screen: the single line equations still have a bit more space above and a lot more below than the multi-line equations.

2021-06-08 07:18 UTC, TobiasWrigstad commented
OK, I will go back and re-read the email. I interpreted it as "too much leading space, good amount of trailing space". I would prefer equal amounts and maybe that was the message and I misinterpreted. 

I'll unify the spaces too as you suggest. I should have thought of that myself.

2021-06-08 07:43 UTC, TobiasWrigstad commented
@martin-henz 

I have updated this PR now -- it is a little tricky to get the spacing right because of the various nested environments involved so I had to resort to measuring on the screen too. 

LaTeX takes the liberty to sometimes stretch these spaces a little to handle page layout issues so please do not check only quantitatively also consider the overall "feel".

2021-06-08 14:47 UTC, martin-henz approved these changes

2021-06-08 14:47 UTC, merged